AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

# Template Information

Description: "{{cookiecutter.project_description}}"

# Global function defaults

Globals:
  Function:
    Runtime: "{{cookiecutter.runtime}}"
    Timeout: {{cookiecutter.timeout}}
    CodeUri: src/

# Template Resources

Resources:

  ExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-my-function"
      Handler: hello.handler

# Template Outputs

Outputs:
  LambdaArn:
    Description: "The created lambda ARN"
    Value: !GetAtt ExampleFunction.Arn


