AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

# Template Information

Description: "{{cookiecutter.project_description}}"

# Template Parameters

Parameters:
  WorkFlowName:
    Type: String
    Description: "The workflow name"
    Default: "{{cookiecutter.stepfunction_name}}"

# Template Resources

Resources:

  MyWorkflowStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Ref WorkFlowName
      DefinitionUri: states/workflow.asl.json
      DefinitionSubstitutions:
        MyParameter: "Hello world!"
  

# Template Outputs

Outputs:
  StepFunctionArn:
    Description: "The StepFunction ARN"
    Value: !Ref MyWorkflowStateMachine


