name: Publish templates zip

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.json }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - id: matrix
        name: Load matrix config
        run: |
          JSON=$(echo $(cat .github/workflows/matrix.json) | sed 's/ //g' )
          echo "::set-output name=json::$JSON"

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        config: ${{fromJson(needs.config.outputs.matrix)}}
    needs: [release, config]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create zip artifacts
      run: zip -r ${{ matrix.config.name }}.zip ${{ matrix.config.path }}

    - name: Upload zip artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ matrix.config.name }}.zip
        asset_name: ${{ matrix.config.name }}.zip
        asset_content_type: application/zip
